# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-Z8NHVQV9ST'

menu:
- {name: 'Blog Posts', url: 'blog_posts.html'}
- {name: 'CV',   url: 'cv.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/kdkalvik'}
- {icon: 'linkedin',   link: 'https://linkedin.com/in/kalvik'}
- {icon: 'ai-google-scholar',   link: 'https://scholar.google.com/citations?user=oZ29YBkAAAAJ&hl=en'}
- {icon: 'envelope',   link: 'mailto:kjakkala@uncc.edu'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
