# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'kalvik'

menu:
- {name: 'Blog Posts', url: 'blog_posts.html'}
- {name: 'Publications', url: 'publications.html'}
- {name: 'CV',   url: 'cv.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/itskalvik'}
- {icon: 'linkedin',   link: 'https://linkedin.com/in/kalvik'}
- {icon: 'instagram',   link: 'https://www.instagram.com/itskalvik/'}
- {icon: 'ai-google-scholar',   link: 'https://scholar.google.com/citations?user=oZ29YBkAAAAJ&hl=en'}
- {icon: 'envelope',   link: 'mailto:kjakkala@uncc.edu'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
